# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gojira < Formula
  desc ""
  homepage "https://github.com/sbvalois/gojira"
  version "1.0.2"

  on_macos do
    url "https://github.com/sbvalois/gojira/releases/download/v1.0.2/gojira_1.0.2_darwin_all.tar.gz"
    sha256 "3467c0b66408309e3bea5292c0ce942a9405cf34b439a01f83f5a90f457122c1"

    def install
      bin.install "gojira"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sbvalois/gojira/releases/download/v1.0.2/gojira_1.0.2_linux_arm64.tar.gz"
      sha256 "9c9ab4231e0946ea2a080abee691ca07a04b395959ba4d095ce4037bb435aecb"

      def install
        bin.install "gojira"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sbvalois/gojira/releases/download/v1.0.2/gojira_1.0.2_linux_amd64.tar.gz"
      sha256 "c2de9f02b31c58302342ee88d627242cab011a63f3aa63536795753e60f3b2e8"

      def install
        bin.install "gojira"
      end
    end
  end
end
